### ISSUE TITLE
Panic during file upload

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#130]
Command :
`cli --conf demo.yaml file upload myfile`

configuration used:
```yaml
organization: zaibonstor                        # itsyou.online organization name
namespace: ns1                                  # itsyou.online namespace
protocol : rest
iyo_app_id: ...
iyo_app_secret: ...

shards:
    - http://127.0.0.1:12345
    - http://127.0.0.1:12346
    - http://127.0.0.1:12347
meta_shards:
    - http://127.0.0.1:2379                     # the address(es) of etcd server

pipes:
    - name: pipe0
      type: chunker
      config:
          chunkSize: 1024000

    - name: pipe1
      type: compress
      config:
          type: snappy

    - name: pipe2
      type: encrypt
      config:
          type: aes_gcm
          privKey: ab345678901234567890123456789012
          nonce: 123456789012

    - name: pipe3
      type: distribution
      config:
          data: 2
          parity: 1
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c0183]

goroutine 1 [running]:
github.com/zero-os/0-stor/client/lib/chunker.(*BlockWriter).WriteBlock(0xc420282b40, 0xc4201b0580, 0x7, 0x8, 0x0, 0x0, 0x0, 0x0, 0xed13a0, 0xc420282b40, ...)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/client/lib/chunker/writer.go:49 +0x443
github.com/zero-os/0-stor/client/pipe.WritePipe.WriteBlock(0xed13a0, 0xc420282b40, 0xc4201b0580, 0x7, 0x8, 0x0, 0x0, 0x0, 0xc420247200, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/client/pipe/write_pipe.go:47 +0x8d
github.com/zero-os/0-stor/client.(*Client).WriteF(0xc420282440, 0xc4201b0580, 0x7, 0x8, 0xed2a20, 0xc42016e190, 0x0, 0x0, 0xc42006ec30)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/client/client.go:86 +0x1a2
main.main.func2(0xc4203d1b80, 0x0, 0xc4203d1b80)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/client/cmd/cli/main.go:55 +0x2f5
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.HandleAction(0xa59bc0, 0xc42014c020, 0xc4203d1b80, 0xc4205ecf00, 0x0)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/app.go:490 +0xd4
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.Command.Run(0xb42e0f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb5a72d, 0x2a, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/command.go:210 +0xb6e
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4201b31e0, 0xc420084c60, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/app.go:379 +0xacf
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.Command.startApp(0xb40e70, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb541c1, 0x20, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/command.go:298 +0x8fa
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.Command.Run(0xb40e70, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb541c1, 0x20, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/command.go:98 +0x13f3
github.com/zero-os/0-stor/vendor/github.com/urfave/cli.(*App).Run(0xc4200a69c0, 0xc4200100c0, 0x6, 0x6, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/vendor/github.com/urfave/cli/app.go:255 +0x76f
main.main()
	/home/zaibon/dev/go/src/github.com/zero-os/0-stor/client/cmd/cli/main.go:223 +0xbce
exit status 2
```
