### ISSUE TITLE
error in etcd when upload files

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#161]
**Description**
ETCD generates an error when I tried to upload a file.

**Enviroment**
- Container_1_0-store: 
- IP : 172.17.0.2 
- has etcd and 0-store 

- Container_2_0-store: 
- IP : 172.17.0.4
- has etcd and 0-store 

- Container_3_client 
- IP : 172.17.0.3
- client 

**client command**
```bash
 ./cli file upload upload_test 
```
**client_config**
```yaml
organization: xtremx90                                # itsyou.online organization name
namespace: xtremx_namespace                                  # itsyou.online namespace
protocol: rest
iyo_app_id: 
iyo_app_secret: 

shards:                                             # the address(es) of 0-stor server
    - http://172.17.0.2:8080
    - http://172.17.0.4:8080
meta_shards:
    - http://172.17.0.2:2379                         # the address(es) of etcd server
    - http://172.17.0.4:2379

pipes:
    - name: pipe0
      type: chunker
      config:
          chunkSize: 1024000

    - name: pipe1
      type: compress
      config:
          type: snappy

    - name: pipe2
      type: encrypt 
      config:
          type: aes_gcm
          privKey: ab345678901234567890123456789012
          nonce: 123456789012

    - name: pipe3
      type: distribution
      config:
          data: 1
          parity: 1
```

**ETCD of container 1 ERROR**
```bash
2017-08-15 16:01:43.843980 I | etcdserver/api/v3rpc: transport: http2Server.HandleStreams failed to read frame: read tcp 172.17.0.2:2379->172.17.0.3:38900: read: connection reset by peer
```
