### ISSUE TITLE
Uploading destoried the file data

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#208]
Uploading destroied the file data.

**Config file:**
```yaml
organization: xtremx90                                # itsyou.online organization name
namespace: namespace_test                                  # itsyou.online namespace
protocol: rest
iyo_app_id: 
iyo_app_secret: 

shards:                                             # the address(es) of 0-stor server
    - http://172.17.0.3:8080
    - http://172.17.0.2:8080
meta_shards:
    - http://172.17.0.2:2379                         # the address(es) of etcd server
    - http://172.17.0.3:2379

pipes:
    - name: pipe0
      type: chunker
      config:
          chunkSize: 1024000

    - name: pipe1
      type: compress
      config:
          type: snappy

    - name: pipe2
      type: encrypt 
      config:
          type: aes_gcm
          privKey: ab345678901234567890123456789012
          nonce: 123456789012


    - name: pipe3
      type: distribution
      config:
          data: 1
          parity: 1

```

**upload/download commands**
![image](https://user-images.githubusercontent.com/17981089/29779880-304117fc-8c14-11e7-93d1-369db25e03f0.png)

**Uploaded file data**
![image](https://user-images.githubusercontent.com/17981089/29779643-743617b0-8c13-11e7-82d6-598b56e88659.png)

**Downloaded file data**
![image](https://user-images.githubusercontent.com/17981089/29779637-6a4ce3be-8c13-11e7-9283-60df85eeb67c.png)

**Original file**
[upload_file_0.gz](https://github.com/zero-os/0-stor/files/1257255/upload_file_0.gz)

**Branch**
Master
