### ISSUE TITLE
Error when download file

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#222]
I got this error when I tried to download a file
**"ERROR! download file failed: invalid number of kvs returned: 0\n ".**

You can reproduce it by doing:
```bash
nosetests-3.4 -vs test_suite/test_cases/basic_tests/test01_upload_download.py:UploadDownload.test001_upload_file --tc-file test_suite/config.ini
```

**Config file**
```yaml
iyo_app_id: rAocsUQLJ_Rm6ktd_M1cjLoH97YW
iyo_app_secret: [secure]
meta_shards:
- http://10.147.17.87:2379
- http://10.147.17.144:2379
- http://10.147.17.171:2379
- http://10.147.17.22:2379
namespace: test
organization: test_zerostor
pipes:
- config:
    chunkSize: 1024000
  name: pipe0
  type: chunker
- config:
    type: snappy
  name: pipe1
  type: compress
- config:
    privKey: ab345678901234567890123456789012
    type: aes_gcm
  name: pipe2
  type: encrypt
- config:
    data: 2
    parity: 1
  name: pipe3
  type: distribution
protocol: rest
shards:
- http://10.147.17.87:8080
- http://10.147.17.144:8080
- http://10.147.17.171:8080
- http://10.147.17.22:8080
```

**Environment**
- Four servers from master 1.1.0-alpha-8
- Client from run_test_suite branch
