### ISSUE TITLE
Uploading multi files in pararrel corrupts at least one file

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#242]
**Description**
Uploading multi files in parallel corrupts at least one file.

**Testing Env.**
3 0-stor servers and 1 etcd

**Config**
```yaml
organization: xtremx90 # itsyou.online organization name
namespace: namespace_test       # itsyou.online namespace
protocol: grpc
iyo_app_id: 
iyo_app_secret: 
data_shards:
    - 172.17.0.2:8080
    - 172.17.0.3:8080
    - 172.17.0.4:8080
meta_shards:
    - http://172.17.0.3:2379
block_size: 124
replication_nr: 3
replication_max_size: 4096
distribution_data: 2
distribution_parity: 1
compress: true
encrypt: true
encrypt_key: 
```

**Execution test case command**
```bash
nosetests-3.4 -vs test_suite/test_cases/basic_tests/test01_upload_download.py:UploadDownload.test001_upload_download_files --tc-file test_suite/config.ini --tc=main.number_of_files:60
```
This test case will create 60 random files, upload them, download them and make sure that they are identical. 

**Result**
```bash
 [*] Number of writer threads: 60
 [*] Compare downloaded files with uploaded files.


{
    "227750914698237898068368677394923450712": {
        "d_info": {
            "md5": "435344b1a1bee6ceb26603d17387050b",
            "path": "/tmp/download/227750914698237898068368677394923450712"
        },
        "u_info": {
            "key": "upload_file_15",
            "md5": "3a7b73fa22ac8e2b8d6400fcb29179ce"
        }
    }
}
FAILED
```
There is one file has been corrupted. 

**Cli & server versions**
f71dc50492b1f2a6201b0252608aa214e19a1320
