### ISSUE TITLE
Writes too slow when using replication

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#256]
During the refactoring of the 0-hub to use 0-stor as backend, we detected that the write are really slow.

Before when using ardb as backend, writing a 39MiB of data to the ardb tooks +- 1 sec
Since we move to 0-stor, it takes more then 1 minute to write the exact same data set.

Configuration used:
```yaml
data_shards:
    - 127.0.0.1:12345
    - 127.0.0.1:12346
    - 127.0.0.1:12347
    - 127.0.0.1:12348
# the address(es) of etcd server
meta_shards:
    - http://localhost:2379
    - http://localhost:22379
    - http://localhost:32379

block_size: 524288

replication_nr: 4
replication_max_size: 524288

distribution_data: 0
distribution_parity: 0

compress: false
encrypt: false
```

So the client that write to the 0-stor use replication. We need to identify why it's so slow.

I did some quick test and it seems that the `replicateWrite` is really not well written and need to be refactored. 

https://github.com/zero-os/0-stor/blob/e276bd02c7a691ae48a51885c0f63b84bf37411c/client/client.go#L422-L511

**Version:**
```
zerostorserver version Version: 0.0.1
Build: e276bd0 2017-09-27T08:08:42+0200
Runtime: go1.9 linux
```

Profiling program: https://play.golang.org/p/wykBwaRRVX
It upload a bunch of file from a directory

Zip containing the profile data set: [flit.zip](https://github.com/zero-os/0-stor/files/1336012/flit.zip)
CLient profiles:
CPU Profile:  [profile001.pdf](https://github.com/zero-os/0-stor/files/1336020/profile001.pdf)
Memory Profile: [profile002.pdf](https://github.com/zero-os/0-stor/files/1336027/profile002.pdf)
Mutex Profile: [profile003.pdf](https://github.com/zero-os/0-stor/files/1336028/profile003.pdf)

Server profiles:
CPU profile:  [profile001.pdf](https://github.com/zero-os/0-stor/files/1336039/profile001.pdf)
