### ISSUE TITLE
ReplicationEnable returns false in case of block size=replication_max_size

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-stor#259]
**Config file:**
```yaml
organization: xtremx90 # itsyou.online organization name
namespace: namespace_test       # itsyou.online namespace
protocol: grpc
iyo_app_id: wrzcIurg4zXEjlJOA1z0CX806jKx
iyo_app_secret: WaKRgZgLTHdTfFEgkrSfieKkd734
data_shards:
    - 172.17.0.2:8080
    - 172.17.0.3:8080
    - 172.17.0.4:8080
meta_shards:
    - http://172.17.0.3:2379
block_size: 4096
replication_nr: 3
replication_max_size: 4096
distribution_data: 2
distribution_parity: 1
compress: true
encrypt: true
encrypt_key: ab345678901234567890123456789012
```

**File Size**
8512

**Steps**
- Upload a file 
- Corrupt the first server data 
- Download the file, check md5 --> OK
- Corrupt the second server data
- Download the file

**Actual result:**
```bash
➜  zerostorcli git:(master) ✗ zerostorcli file download test test2
WARN[0000] replication read, error reading from 172.17.0.2:8080: rpc error: code = Unknown desc = Unable to read from value log: {Fid:0 Len:3009 Offset:624405775}: EOF 
file downloaded to test2. referenceList=[]
➜  zerostorcli git:(master) ✗ md5sum test2                        
f0de955eb1b137ea18fd0a7cbdaa62c1  test2
➜  zerostorcli git:(master) ✗ zerostorcli file download test test3
download file failed: [{"addrs":["172.17.0.2:8080"],"kind":"0-stor","error":{"code":2,"message":"Unable to read from value log: {Fid:0 Len:4960 Offset:624395855}: EOF"},"code":400},{"addrs":["172.17.0.3:8080"],"kind":"0-stor","error":{"code":2,"message":"Unable to read from value log: {Fid:0 Len:4960 Offset:331080984}: EOF"},"code":400}]
```

**File metadata**
```json
{
   "previous" : null,
   "chunks" : [
      {
         "size" : 4129,
         "key" : "prC8Cg1w4tvuR4FmxQomZknRS/5HzMRnjRvyHRYmXqc=",
         "shards" : [
            "172.17.0.3:8080",
            "172.17.0.2:8080",
            "172.17.0.4:8080"
         ]
      },
      {
         "key" : "5RkhNIDXjMlIWQT2/s7Jy1jpMs8IOZ39bNp6ToBkv14=",
         "size" : 4129,
         "shards" : [
            "172.17.0.3:8080",
            "172.17.0.2:8080",
            "172.17.0.4:8080"
         ]
      },
      {
         "shards" : [
            "172.17.0.3:8080",
            "172.17.0.2:8080",
            "172.17.0.4:8080"
         ],
         "key" : "iyVfsER+sbklY8JL1V9Ydk/zqNyZoo1h+gnbjO4g6Qo=",
         "size" : 353
      }
   ],
   "next" : null,
   "configPtr" : null,
   "key" : "dGVzdA==",
   "encryption_key" : "YWIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=",
   "epoch" : 1506592770087426830
}
```

**Server version**
e276bd02c7a691ae48a51885c0f63b84bf37411c

**client version**
e276bd02c7a691ae48a51885c0f63b84bf37411c
