### ISSUE TITLE
Client benchmark program

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#380]
As part of #296 we need a program that can benchmark and profile the client with different configurations

* block size
* replication
* distribution
* hashing algo
* encryption algo
* amount of 0-stor servers
* number of (concurrent) clients connected to the servers

**Comment by katia-e** [comment]
## Workload flow for client benchmarking:
1. Client reads clientConfig.yaml* and parses the following:
  * 0-stor server config
  * set of configurations for benchmarking
  * profiling flags
2. Client runs benchmarking and optionally profiling
3. Clients outputs benchmarking results into a new yaml file
________________________
*clientConfig.yaml, specific for the client benchmarking tool, is generated at the orchestrator. It is a work of the orchestrator to start 0-stor servers before running client benchmarking tool and fetch results after the benchmarking is finished

**Comment by katia-e** [comment]
## Output format questions:

Desirable output format have to be defined. Currently the flow is the following:
1. Input for the orchestrator: template config file, name of varying parameter and range of values
2. The orchestrator creates a config file based on the given template with several scenarios with only one parameter difference and triggers the benchmarking program.
3. The benchmarking program loops over given scenarios and returns output file
4. The orchestrator parses the output file and presents a MD document with the following content:
     * plots of number_of_operations vs timeline (if parameter per_interval is given in the config)
     * a plot of throughput vs parameter
     * config file

The following parameters can be changed for the purpose of benchmarking (values can be given as range):
``` yaml
      block_size: 2048
      replication_nr: 2
      replication_max_size: 4096
      distribution_data: 2
      distribution_parity: 1
      compress: true
      encrypt: false
      key_size: 48
      ValueSize: 128
```

Open questions:
1. How to create unified report format for all sorts of benchmarking tests taking to account different nature of parameters (some are integers, some are string etc.)?
2. Should the figures be complemented by the tables with numerical values corresponding to the plots, or not?
3. Currently the range of parameters and the parameter's name are given as a part of a config file for orchestrator, together with the template config for client. Should it be done differently?(in a separate file or another way)
4. Should the results be provided for combination of varying parameters? It can be good for the sake of visual representation of data (for example to plot throughput vs block_size with and without encryption).

**Comment by zaibon** [comment]
> Should the figures be complemented by the tables with numerical values corresponding to the plots, or not?

Yes I think a table with the result is also nice

> Currently the range of parameters and the parameter's name are given as a part of a config file for orchestrator, together with the template config for client. Should it be done differently?(in a separate file or another way)

Part of the config file is fine for me


> Should the results be provided for combination of varying parameters? It can be good for the sake of visual representation of data (for example to plot throughput vs block_size with and without encryption).

Yes. the kind of graph like throughput vs block_size  is something we want.

> How to present results for the case of concurrent clients?

I would say:
-  thoughput VS number of concurent client
- average time per action VS number of concurent client

**Comment by zaibon** [comment]
Would also be cool to have some histogram graphs of the throughput based on different key/value size.
And we could have these histogram for different configurations

**Comment by katia-e** [comment]
## Output format of the benchmarking

 1. Support ranging over possible variables for the following parameters:
  * int
           * block_size
           * ValueSize
           * clients
           * replication_nr (?)
           * distribution_data
  * bool
           * encrypt
           * compress
 * string
           * method : read, write
           * hashing algo (? was mentioned in issue, but not in config)


2. Support output for combination of parameters
            * Orchestrator config includes configuration of the tests in the following yaml formal
``` yaml
scenarios:
  benchName:
    benchmarks:
    -prime_parameter:
        id: block_size
        range: 128, 256,  512, 1024, 2048, 4096
      second_parameter:
        id: encrypt
        range: true, false
    template:
      zstor_config:
        data_shards:
          - 127.0.0.1:12345
          - 127.0.0.1:12346
          - 127.0.0.1:12347
        meta_shards:
          - 127.0.0.1:2379
        block_size: 2048
        replication_nr: 2
        replication_max_size: 4096
        distribution_data: 2
        distribution_parity: 1
        compress: true
        encrypt: false
        encrypt_key: ab345678901234567890123456789012
      bench_conf:
        clients: 1
        method: write
        result_output: per_second
        duration: 10
        operations: 0
        key_size: 48
        ValueSize: 128

```
             * several benchmarks can be defined
             * if `benchmarks` if empty, the benchmark will run for a single scenario, provided in `template`
             * if only `prime_parameter` is given, results are provided by ranging this parameter
             * if both `prime_parameter` and `second_parameter` are provided, the figures will depict throughput vs  prime_parameter: id, and combine several plots for different `second_parameter`

 3. output bar plots in the following format:

![block_size](https://user-images.githubusercontent.com/32639869/33953711-40b4d01c-e036-11e7-95ca-f5cdf0832a51.png)
![block_size2](https://user-images.githubusercontent.com/32639869/33953713-40d1283e-e036-11e7-8d61-a6541dfe1d85.png)
![block_size3](https://user-images.githubusercontent.com/32639869/33953714-40e967b4-e036-11e7-9aaa-8071cfbaa324.png)

**Comment by katia-e** [comment]
## Issue 1 in current version of `zstor` benchmark
* Error when number of concurrent clients more than 1:
``` bash
panic: runtime error: index out of range

goroutine 118 [running]:
github.com/zero-os/0-stor/benchmark/benchers.(*WriteBencher).RunBenchmark(0xc4202c60f0, 0x0, 0x0, 0x0)
        /home/katia/go/src/github.com/zero-os/0-stor/benchmark/benchers/writebencher.go:87 +0x852
github.com/zero-os/0-stor/cmd/zstorbench/cmd.root.func1(0xc420053b80, 0xc420053b70, 0xc420152e60, 0xc420014e30, 0xe95300, 0xc42000e9b0, 0x0)
        /home/katia/go/src/github.com/zero-os/0-stor/cmd/zstorbench/cmd/root.go:123 +0x37
created by github.com/zero-os/0-stor/cmd/zstorbench/cmd.root
        /home/katia/go/src/github.com/zero-os/0-stor/cmd/zstorbench/cmd/root.go:121 +0x95d
```

Reproduce steps:
                  1. cd benchmark/orchestrator/
                  2. in `orchConfig.yaml` set `clients: 2`
                  3. run python3 `orchestrator`

**Comment by katia-e** [comment]
## Issue 2 in current version of zstor benchmark
* Results of the benchmark in `benchmarkResult.yaml` in field `per_interval` often do not checkout. This situation repeats with different configs. Example of the output:
```
  results:
  - count: 934
    duration: 10.003072
    perinterval:
    - 1
    - 66
    - 100
    - 118
    - 113
    - 110
    - 98
    - 107
    - 101
    - 109
    - 109
``` 
Manually adding operations `perinterval` we have 1032. It doesn't check out with `count: 934`. 
Moreover, perhaps, first count `-1` should be the last, as it corresponds to the last `0.003072` seconds.

**Comment by katia-e** [comment]
## Issue 3 in current version of zstor benchmark
 * In `bench_conf` if `duration` is non zero and `operations` is 0, the benchmark should run for given duration. In reality it limmits number of operations to 1000 operations.
Example of bench config:
``` yaml
bench_conf:
      ValueSize: 128
      clients: 1
      duration: 100
      key_size: 48
      method: write
      operations: 0
      result_output: per_second
```
produced result:
``` yaml
results:
    - count: 991
      duration: 9.551445
      perinterval:
      - 38
      - 105
      - 122
      - 114
      - 100
      - 101
      - 98
      - 109
      - 106
      - 106
      bench_conf:
        method: write
        result_output: per_second
        duration: 100
        operations: 1000
        clients: 1
        key_size: 48
        ValueSize: 128
```

**Comment by chrisvdg** [comment]
For issue 2, I think the use of the ratecounter package causes the inconsistency. the `perinterval` values now don't really represent the true ops in that interval but the ratecounters rate of ops in it's current interval.
So either we count the ops per interval ourselves again, so `perinterval` represents the ops per interval again or keep it as it is and `perinterval` represents the ops rate per interval

**Comment by katia-e** [comment]
@chrisvdg , what does "rate of ops" mean in this context? Where do we need to count it again if we want to know number of ops in the given time interval?

**Comment by chrisvdg** [comment]
It's the operations/interval (also with a resolution within that interval), the interval  of the ratecounter is set to be the same as the bench client's interval but it's not synced.
To get the actual ops per interval we would just add another counter int that keeps track of the ops within the current interval like we did first.

**Comment by zaibon** [comment]
I don't understand this. How could it not be in synced ? the interval it base on time. And AFAIK time is the same for everyone. So I how could that be a problem ?
It seems that the problem is more that we start the rate counter too soon or stop it too late.
But even then. On a long run this doesn't really impact the results.

**Comment by katia-e** [comment]
Setting up `zstor` and `etcd` server presumes automatically choosing ports for it. Few questions have raised in this regard:
 1. Should we kill processes on chosen ports in case if the ports are occupied by something else (perhaps, previously started `zstore` if the benchmark wasn't closed correctly)?

2. If we should kill them, which command to use? I've been using `kill -9` for my tests, because nothing else kills it, maybe there is a better alternative.

**Comment by GlenDC** [comment]
How are you starting ports? If you start them with a tcp listener, you can start a listening on a random open port using `listener, err := net.Listen("tcp", "localhost:0")`. Afterwards you can then use `listener.Addr().String()` in order to get the local address, including the assigned port.

> (perhaps, previously started zstor if the benchmark wasn't closed correctly)?

I don't see how this would happen ever, ever. I can only see it happen if there is a panic in your orchestrator, which means you have a bug. If no panic happens and this still happens, you still have a bug.

for ETCD I'm not too sure. You might have to start an etcd server using your custom `main.go` file for benchmarking purposes, so you can easily configure them (using https://godoc.org/github.com/coreos/etcd/etcdserver#NewServer) but perhaps that's not possible. Perhaps there's a way to do it from the config, dunno. You would have to look into it.

In worst case you just make sure to document that the user has to reserve a certain range of ports for ETCD purposes, when running the benchmark tools. Than you just have to make sure to always shut them down.

> If we should kill them, which command to use?

Obviously you should kill them when you're done with them. But is this the case only if you're also the ones that started them! If so, you can use something like https://godoc.org/os#Process.Kill

**Comment by chrisvdg** [comment]
@GlenDC, the orchestrator is written in python btw

**Comment by GlenDC** [comment]
What... What.... Why o.O O.o O.O Why :(

(even so, I'm sure you can do the same stuff in python as I described here, but I'm too lazy to search the python documentation for you)

(still... whyyyyyy, please convince me why that was needed)

**Comment by chrisvdg** [comment]
@zaibon suggested it so we could use python libs to plot the graphs and use jumpscale for deploying (packet.net which I'm working on right now), so we gave it a try

**Comment by katia-e** [comment]
@GlenDC, servers may keep running in case if the orchestrator was manually interrupted, and then run again. We do close servers in python after we are done with them, but it happens only if we reach ench of the code. But I wanted to check ports prior to benchmarking, and if they are not free, close running processes with `bash` command. We did think of choosing random pots, but were afraid that if previous benchmark not closed correctly, the servers will keep running and affect the next benchmark. In case if we use the same ports every time, we exclude this problem.

**Comment by GlenDC** [comment]
> libs to plot the graphs

Golang has nice ibs for plotting graphs too AFAIK.

> use jumpscale for deploying (packet.net which I'm working on right now)

not sure why you need python for that. Well deployment I mean. Even so, that could be easily a separate part of the project, not sure why all the rest has to be in python for just that tiny part.

**Comment by GlenDC** [comment]
> servers may keep running in case if the orchestrator was manually interrupted, and then run again.

You'll need to listen to any incoming SIGINT signals, in which case you need to start your graceful exit, which includes stopping all servers you've started.

> We do close servers in python after we are done with them, but it happens only if we reach ench of the code

this is BAD, servers started should always close, always

> were afraid that if previous benchmark not closed correctly, the servers will keep running and affect the next benchmark

You are solving a non-existent problem. If your code is correct, your servers should always be exited just fine. If the user is running benchmarks on a non-idle computer, he is doing it wrong and so that's his responsibility. You just need to make sure that your benchmarker tool cleans up everything he made messy :)

**Comment by katia-e** [comment]
# Example of the benchmark results
## Report 1
![fig1](https://user-images.githubusercontent.com/32639869/34982002-79cf5eb6-faa9-11e7-97aa-4669cf23212c.png)

 <h3> Throughput, byte/s: </h3>
            <head> 
                <style>
                    table, th, td {
                        border: 1px solid black;
                        border-collapse: collapse;
                    }
                    th, td {
                        text-align: left;    
                    }
                </style>
            </head>
            <table>  
                <tr> <th> value_size</th><th> key_size = 32 </th><th> key_size = 64 </th><th> key_size = 128 </th> </tr> <tr> <th> 128 </th><th> 7886 </th><th> 7933 </th><th> 7865 </th></tr><tr> <th> 256 </th><th> 16407 </th><th> 16443 </th><th> 16343 </th></tr><tr> <th> 512 </th><th> 31811 </th><th> 31651 </th><th> 31534 </th></tr><tr> <th> 1024 </th><th> 66134 </th><th> 63077 </th><th> 64980 </th></tr><tr> <th> 2048 </th><th> 126288 </th><th> 125408 </th><th> 124560 </th></tr><tr> <th> 4096 </th><th> 249719 </th><th> 255743 </th><th> 254189 </th></tr><tr> <th> 8192 </th><th> 425994 </th><th> 433928 </th><th> 423745 </th></tr>
 </table></details>
**Benchmark config:** 

```yaml 
scenario:
  bench_config:
    clients: 1
    duration: 500
    key_size: 128
    method: write
    operations: 0
    result_output: per_minute
    value_size: 8192
  zstor_config:
    pipeline:
      block_size: 4096
      compression:
        mode: default
        type: snappy
      distribution:
        data_shards: 3
        parity_shards: 1
      encryption:
        private_key: ab345678901234567890123456789012
        type: aes
```
## Report 2
![fig2](https://user-images.githubusercontent.com/32639869/34982186-fd7f8a56-faa9-11e7-8688-a7cb616ef64c.png)
<h3> Throughput, byte/s: </h3>
            <head> 
                <style>
                    table, th, td {
                        border: 1px solid black;
                        border-collapse: collapse;
                    }
                    th, td {
                        text-align: left;    
                    }
                </style>
            </head>
            <table>  
                <tr> <th> data_shards</th><th> clients = 1 </th><th> clients = 2 </th><th> clients = 3 </th> </tr> <tr> <th> 1 </th><th> 12579 </th><th> 10920 </th><th> 9566 </th></tr><tr> <th> 2 </th><th> 10182 </th><th> 8301 </th><th> 7198 </th></tr><tr> <th> 5 </th><th> 5928 </th><th> 4997 </th><th> 4348 </th></tr><tr> <th> 10 </th><th> 3435 </th><th> 2890 </th><th> 2633 </th></tr><tr> <th> 20 </th><th> 1904 </th><th> 1606 </th><th> 1471 </th></tr>
 </table></details>

**Benchmark config:** 

```yaml 
scenario:
  bench_config:
    clients: 3
    duration: 500
    key_size: 48
    method: write
    operations: 0
    result_output: per_minute
    value_size: 128
  zstor_config:
    pipeline:
      block_size: 4096
      compression:
        mode: default
        type: snappy
      distribution:
        data_shards: 20
        parity_shards: 1
      encryption:
        private_key: ab345678901234567890123456789012
        type: aes

```

**Comment by katia-e** [comment]
# Benchmark results for `1.1.0-beta-2` on `packet.net`
**Benchmark config:** 
```yaml 
scenario:
  bench_config:
    clients: 1
    duration: 60
    key_size: 48
    method: write
    operations: 0
    result_output: per_second
    value_size: 10000000
  zstor_config:
    pipeline:
      block_size: 10000
      compression:
        mode: default
        type: gzip
      distribution:
        data_shards: 2
        parity_shards: 1
      encryption:
        private_key: ''
        type: aes

```
![fig1](https://user-images.githubusercontent.com/32639869/35582047-e2380d14-05ed-11e8-8a26-3166dce3b69c.png)

 ### Throughput: 
| value_size | block_size = 2.0 kB |block_size = 50.0 kB |block_size = 10.0 kB | 
|---|---|---|---| 
 | 512 Bytes |88.5 kB/s |89.1 kB/s |90.5 kB/s | 
| 1.0 kB |168.3 kB/s |169.1 kB/s |172.5 kB/s | 
| 10.0 kB |673.6 kB/s |1.5 MB/s |1.5 MB/s | 
| 3.0 MB |1.1 MB/s |9.7 MB/s |4.7 MB/s | 
| 10.0 MB |1.1 MB/s |10.0 MB/s |4.8 MB/s |

**Comment by GlenDC** [comment]
All those numbers look really bad, what was your connection speed?

Can you repeat the same for master? Would like to see the difference.

Also, for your exported graph, would it be possible to somehow rotate those numbers, so they don't overlap, as now you can't really see them when they are next to one another and of equal height.

**Comment by katia-e** [comment]
I'm fixing the number, just wanned to attach some results already.

Don't know the connection speed,  this is the connection between devices on `packet.net`, how do I check it?
Which numbers would be good to have? Throughput depends on the `block_size` and the `value_size`. I'll run benchmark for larger blocks and numbers will be higher.

I'll run this benchmark for master tomorrow.

**Comment by zaibon** [comment]
Indeed the block size here are not really useful. You need a block size of at least 1MiB. you can go to 5, 10MiB even for some use case.

**Comment by katia-e** [comment]
## Benchmark on packet.net for `1.1.0-beta-2`
![fig1](https://user-images.githubusercontent.com/32639869/35746454-247bdeac-0847-11e8-9ea4-ab09a648b7f2.png)


 # Report 1 
**Benchmark config:** 
```yaml 
scenario:
  bench_config:
    clients: 10
    duration: 30
    key_size: 64
    method: write
    operations: 0
    result_output: per_second
    value_size: 10000000
  zstor_config:
    pipeline:
      block_size: 10485760
      compression:
        mode: default
        type: snappy
      distribution:
        data_shards: 1
        parity_shards: 0
      encryption:
        private_key: ''
        type: aes

```

 ### Throughput: 
| block_size | clients = 1 |clients = 5 |clients = 10 | 
|---|---|---|---| 
 | 1.0 MiB |57.8 MiB/s |12.9 MiB/s |6.5 MiB/s | 
| 5.0 MiB |40.1 MiB/s |11.7 MiB/s |5.7 MiB/s | 
| 10.0 MiB |32.6 MiB/s |12.5 MiB/s |5.7 MiB/s |
