### ISSUE TITLE
reading from 0-stor after multiple entries raises error

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-stor#529]
## setup
Branch: `dev-tft-launch`

I run `0-stor` locally with the below configuration
```yaml
namespace: default
datastor:
  shards:
    - 127.0.0.1:9900
metastor:
  db:
    endpoints:
      - 127.0.0.1:2379
```
I use a generated `grpc` templates from the schemas in the repo to interact with `0-stor`

## scenario
* I push binary k(b"default.0.1")/v pair to 0-stor
* I get the pair k(b"default.0.1") and it works fine
* I push another binary k(b"default.1.1")/v pair to 0-stor
* I try to get k(b"default.0.1") again, then I get `returned object has invalid data size`
