### ISSUE TITLE
[CLOSED] Configuration of the lib

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-stor#85]
<a href="https://github.com/zaibon"><img src="https://avatars2.githubusercontent.com/u/303164?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zaibon](https://github.com/zaibon)**
_Monday Jul 17, 2017 at 07:21 GMT_
_Originally opened as https://github.com/zero-os/0-stor-lib/issues/16_

----

Goal: We need to be able to persist the configuration of the lib used during the creation of the data. 
This is needed when we'll need to retrieve the data back.

Requirements:
- The configuration should contain all the configuration of each component
- Configuration should be serializable in a compact format, so we can save it in the metadata server easily without consuming too much storage.
- From the configuration, the library knows how to do to put/get data out of the 0-stor. This is the only input the lib needs.

**Comment by iwanbk** [comment]
<a href="https://github.com/iwanbk"><img src="https://avatars1.githubusercontent.com/u/977552?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [iwanbk](https://github.com/iwanbk)**
_Monday Jul 17, 2017 at 07:37 GMT_

----

> Configuration should be serializable in a compact format, so we can save it in the metadata server easily without consuming too much storage.


> From the configuration, the library knows how to do to put/get data out of the 0-stor. This is the only input the lib needs.

Although use morre storage, i suggest to use yaml instead of capnp.
the configuration would be like this
```yaml
name: client
pipes:
   - name: pipe1
     type : compress
     configs:
          field1: ..
          field2: ...
   - name: pipe2
     type : encrypt
     configs:
          field1: ..
          field2: ..
```
`configs` there is `map[string]interface`, when we see `compress` then we `cast` that `map[string]interface{}` to `compress.Config`
